"""Change refills.due_date from DATE to TIMESTAMPTZ so fills can carry a specific time-of-day,
not just a calendar date. Existing rows retain their dates with time defaulting to 00:00:00 UTC.

Revision ID: ca862f469d54
Revises: 016
Create Date: 2026-04-09 23:07:28.650148
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca862f469d54'
down_revision = '016'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refills', 'due_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refills', 'due_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
