"""change_fill_dates_to_datetime

Change refills.completed_date, refill_hist.completed_date, and refill_hist.sold_date
from DATE to TIMESTAMPTZ so that the exact time of fill completion and sale is preserved.

Revision ID: 72bbf0fcbd07
Revises: ca862f469d54
Create Date: 2026-04-10 05:31:30.849550
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72bbf0fcbd07'
down_revision = 'ca862f469d54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refill_hist', 'completed_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('refill_hist', 'sold_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('refills', 'completed_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refills', 'completed_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('refill_hist', 'sold_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('refill_hist', 'completed_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
